ci(readiness):simplified navigation-consistency step

diff --git a/.github/workflows/reusable-readiness-assessment.yml b/.github/workflows/reusable-readiness-assessment.yml
--- a/.github/workflows/reusable-readiness-assessment.yml
+++ b/.github/workflows/reusable-readiness-assessment.yml
@@ -1,7 +1,11 @@
 name: Readiness Assessment
 
 on:
-  workflow_call
+  workflow_call:
+    inputs:
+        repo_name:
+          required: true
+          type: string
 
 permissions:
   contents: read
@@ -28,39 +32,40 @@ jobs:
     name: Check Navigation is consistent with our standards.
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v7
-      - name: Get App Info
-        id: app
-        run: |
-          MANIFEST="app.manifest"
-          APP_CONF="default/app.conf"
-          if [ -f "$MANIFEST" ]; then
-            app_id=$(cat "$MANIFEST" | jq -r '.info.id.name')
-            app_version=$(cat "$MANIFEST" | jq -r '.info.id.version')
-            echo "name=${app_id}" >> $GITHUB_OUTPUT
-            echo "version=${app_version}" >> $GITHUB_OUTPUT
-          elif [ -f "$APP_CONF" ]; then
-            app_pck_id=$(crudini --get "$APP_CONF" package id 2>/dev/null || echo "")
-            app_id=$(crudini --get "$APP_CONF" id name 2>/dev/null || echo "")
-            if [ -z "$app_pck_id" ] && [ -z "$app_id" ]; then
-              echo "App Info Missing ❌ Please add 'package/app.manifest' or stanza [package] with id in 'package/default/app.conf' as per https://docs.splunk.com/Documentation/Splunk/latest/Admin/Appconf#.5Bpackage.5D"
-              exit 1
-            fi
-            if [ -z "$app_id" ]; then
-              app_id=$app_pck_id
-            fi
-            app_version=$(crudini --get "$APP_CONF" launcher version 2>/dev/null || echo "")
-            echo "name=${app_id}" >> $GITHUB_OUTPUT
-            echo "version=${app_version}" >> $GITHUB_OUTPUT
-          else
-            echo "Files Not Found ❌ Please add 'package/app.manifest' or 'package/default/app.conf'"
-            exit 1
-          fi
-        working-directory: ./package
+      # - uses: actions/checkout@v7
+      # - name: Get App Info
+      #   id: app
+      #   run: |
+      #     MANIFEST="app.manifest"
+      #     APP_CONF="default/app.conf"
+      #     if [ -f "$MANIFEST" ]; then
+      #       app_id=$(cat "$MANIFEST" | jq -r '.info.id.name')
+      #       app_version=$(cat "$MANIFEST" | jq -r '.info.id.version')
+      #       echo "name=${app_id}" >> $GITHUB_OUTPUT
+      #       echo "version=${app_version}" >> $GITHUB_OUTPUT
+      #     elif [ -f "$APP_CONF" ]; then
+      #       app_pck_id=$(crudini --get "$APP_CONF" package id 2>/dev/null || echo "")
+      #       app_id=$(crudini --get "$APP_CONF" id name 2>/dev/null || echo "")
+      #       if [ -z "$app_pck_id" ] && [ -z "$app_id" ]; then
+      #         echo "App Info Missing ❌ Please add 'package/app.manifest' or stanza [package] with id in 'package/default/app.conf' as per https://docs.splunk.com/Documentation/Splunk/latest/Admin/Appconf#.5Bpackage.5D"
+      #         exit 1
+      #       fi
+      #       if [ -z "$app_id" ]; then
+      #         app_id=$app_pck_id
+      #       fi
+      #       app_version=$(crudini --get "$APP_CONF" launcher version 2>/dev/null || echo "")
+      #       echo "name=${app_id}" >> $GITHUB_OUTPUT
+      #       echo "version=${app_version}" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "Files Not Found ❌ Please add 'package/app.manifest' or 'package/default/app.conf'"
+      #       exit 1
+      #     fi
+      #   working-directory: ./package
 
       - name: Verify availability of required links in app navigation
         env:
-          APP_ID: ${{ steps.app.outputs.name }}
+          # APP_ID: ${{ steps.app.outputs.name }}
+          APP_ID: ${{ inputs.repo_name }}
         run: |
           set -euo pipefail
           NAV_FILE="default/data/ui/nav/default.xml"
